###############################################################################
#                                 Slack Tim List                              #
###############################################################################
slack_teams:
  T0001 :
    team_name:            TIM A
    slash_command_token:  yfUzr6Il4XWwxKYOoiNNSzhA
    incoming_webhook_url: |
        https://hooks.slack.com/commands/1234/5678

###############################################################################
#                             EC2 Instance List                               #
###############################################################################
instances:
  instance-a-01:
    id :                  i-02349305d23a2e7d5
    region :              ap-south-1
    slack_team_id:        T0001




###############################################################################
#                             Scheduled Instances                             #
###############################################################################
scheduled_events:
  week_days_8_am:
    scheduled_expression: cron(0 1 ? * MON-FRI *)
    command:              start
    state :               ENABLED
    instances:
      - instance-a-01

  week_days_7_pm:
    scheduled_expression: cron(0 15 ? * MON-FRI *)
    command:              stop
    state :               DISABLED
    instances:
      - instance-a-01

  custom:
    scheduled_expression: rate(2 minutes)
    command:              stop
    state :               DISABLED
    instances:
      - instance-a-01
